Repository emnify/product-docs, pull requests merged in 2023-01, with the labels that each got.

#9 Publish updated Data Streamer documentation
  docs/data-streamer/available-integrations.md
  docs/data-streamer/connection-types.md
  docs/data-streamer/getting-started.md
  docs/data-streamer/managing-data-streams.md
  docs/data-streamer/stream-types.md
  docs/data-streamer/usage.md
  docs/integration/assets/Logo-web_logo-white-onblue.png
  docs/integration/assets/datastreamer-view-wialon-flespi.web
  docs/integration/assets/image-png-Mar-14-2022-08-29-05-56-PM.png
  docs/integration/assets/image-png-Mar-14-2022-08-55-41-91-PM.png
  docs/integration/assets/image-png-Mar-14-2022-09-35-52-65-PM.png
  docs/integration/assets/image-png-Mar-14-2022-09-44-52-22-PM.png
  docs/integration/assets/image-png-Mar-14-2022-09-47-14-16-PM.png
  docs/integration/assets/image-png-Mar-14-2022-09-51-23-31-PM.png
  docs/integration/assets/image-png-Mar-14-2022-10-04-49-96-PM.png
  docs/integration/assets/image-png-Mar-15-2022-04-10-04-69-PM.png
  docs/integration/assets/image-png-Mar-15-2022-05-05-51-38-PM.png
  docs/integration/assets/image-png-Mar-15-2022-05-11-33-39-PM.png
  docs/integration/assets/image-png-Mar-15-2022-05-17-59-14-PM.png
  docs/integration/assets/image-png-Mar-15-2022-06-26-54-38-PM.png
  docs/integration/assets/image-png-Mar-15-2022-06-46-25-13-PM.png
  docs/integration/assets/image-png-Mar-15-2022-06-50-51-27-PM.png
  docs/integration/assets/image-png-Mar-17-2022-04-57-21-86-PM.webp
  docs/integration/assets/image-png-Mar-17-2022-05-14-54-84-PM.webp
  docs/integration/assets/image-png-Mar-17-2022-05-17-15-62-PM.webp
  docs/integration/assets/image-png-Mar-23-2022-06-58-34-56-PM.webp
  docs/integration/assets/image-png-Mar-23-2022-07-15-26-87-PM.webp
  docs/integration/assets/image-png-Mar-23-2022-07-40-23-87-PM.webp
  docs/integration/assets/image-png-Mar-23-2022-08-21-56-60-PM.webp
  docs/integration/assets/image-png-Mar-23-2022-08-23-48-45-PM.webp
  docs/integration/datastreamer-wialon-flespi.md
  docs/service-stack-overview.md
  docs/services.md
  sidebars.js
Labels: Approved

#17 Remove placeholder blog and clean up config file
  blog/2019-05-28-first-blog-post.md
  blog/2019-05-29-long-blog-post.md
  blog/2021-08-01-mdx-blog-post.mdx
  blog/2021-08-26-welcome/docusaurus-plushie-banner.jpeg
  blog/2021-08-26-welcome/index.md
  blog/authors.yml
  docusaurus.config.js
Labels: bug, Approved

#16 Implement first iteration of the footer
  docusaurus.config.js
Labels: ready for review

#15 Create generated-index for SSO category
  docs/sso/google-cloud-platform.md
  docs/sso/microsoft-active-directory.md
  docs/sso/overview.md
  docs/sso/troubleshooting.md
  sidebars.js
Labels: enhancement

#18 Clean up sidebar file
  sidebars.js
Labels: enhancement

#19 Add context to package.json file
  package.json
Labels: enhancement

#28 Update and publish screenshots for Data Streamer documentation
  docs/services/data-streamer/assets/aws-s3-bucket-permissions-blocking-public-access.png
  docs/services/data-streamer/assets/aws-s3-bucket-properties-encryption.png
  docs/services/data-streamer/assets/portal-integrations-data-streams-add-buttons.png
  docs/services/data-streamer/assets/portal-integrations-data-streams-add-new-button.png
  docs/services/data-streamer/assets/portal-integrations-data-streams-details-events-filter.png
  docs/services/data-streamer/assets/portal-integrations-data-streams-details-usage.png
  docs/services/data-streamer/assets/portal-integrations-data-streams-panel.png
  docs/services/data-streamer/assets/portal-integrations-data-streams-status.png
  docs/services/data-streamer/available-integrations.md
  docs/services/data-streamer/usage.md
Labels: enhancement

#8 Migrate the Quickstart guide
  docs/assets/MOSMS.png
  docs/assets/TGW.png
  docs/assets/bic.png
  docs/assets/capture.png
  docs/assets/create_device.png
  docs/assets/eDRX.png
  docs/assets/edrx.png
  docs/assets/mosms.png
  docs/assets/psm.png
  docs/assets/qrscan.png
  docs/assets/register_batch_sim.png
  docs/assets/register_sim_complete.png
  docs/assets/register_sims.png
  docs/assets/register_single_sim.png
  docs/assets/tgw.png
  docs/quickstart.md
  docs/quickstart/assets/attached.png
  docs/quickstart/assets/offline.png
  docs/quickstart/assets/online.png
  docs/quickstart/assets/reset_connectivity.png
  docs/quickstart/devices/android.md
  docs/quickstart/devices/cellular-modules.md
  docs/quickstart/devices/creating-a-device.md
  docs/quickstart/devices/getting-the-first-device-online.md
  docs/quickstart/devices/gps-trackers.md
  docs/quickstart/devices/industrial-routers.md
  docs/quickstart/devices/ios-devices.md
  docs/quickstart/getting-started.md
  docs/quickstart/registering-sims.md
  docs/quickstart/troubleshooting.md
  docs/services/business-intelligence-and-analytics-reports.md
  docs/services/endpoint-management-and-group-policies.md
  docs/services/iot-cloud-communication-platform.md
  docs/services/no-code-workflow-automation.md
  sidebars.js
  static/img/create_device.png
  static/img/docusaurus.png
  static/img/logo.png
  static/img/offline.png
Labels: ready for review

#25 SEO: Add global metadata, fix page metadata
  docs/services/data-streamer/getting-started.md
  docs/services/events/getting-started.md
  docusaurus.config.js
  sidebars.js
Labels: ✨ Enhancement

#30 Apply temporary distinguished style for details elements
  docs/services/data-streamer/stream-types.md
  docusaurus.config.js
  src/css/custom.css
Labels: 🎨 Design

#33 Update content and design of 404 page
  src/theme/NotFound.js
  src/theme/NotFound.module.css
Labels: ✨ Enhancement, 🎨 Design

#32 Clean up language and formatting on REST API page
  docs/rest-api.md
Labels: ✏️ Editorial

#34 Add supplementary screenshots to Events usage docs
  docs/services/assets/portal-integrations-data-streams-details-events-filter.png
  docs/services/assets/portal-integrations-data-streams-status.png
  docs/services/data-streamer/usage.md
  docs/services/events/assets/portal-connected-devices-details-events.png
  docs/services/events/assets/portal-dashboard-event-details.png
  docs/services/events/assets/portal-dashboard-events.png
  docs/services/events/assets/portal-sim-inventory-details-events.png
  docs/services/events/usage.md
Labels: 🎨 Design

#35 Add important property to collapsible content top border override
  src/css/custom.css
Labels: 🪲 Bug, 🎨 Design

#36 Remove MNO and reseller event types
  docs/services/events/mno-events.md
  sidebars.js
Labels: ✏️ Editorial

#37 Improve footer design, add links to Imprint and Privacy Policy
  docusaurus.config.js
  static/img/logo-icon-only-dark.svg
Labels: ✨ Enhancement, 🎨 Design

#40 Temporary fix for collapsible content top border override (round two)
  src/css/custom.css
Labels: 🪲 Bug, 🎨 Design

#39 Convert REST API page into category
  docs/rest-api/authentication.md
  docs/rest-api/getting-started.md
  docs/rest-api/sms-operations.md
  sidebars.js
Labels: ✏️ Editorial, ✨ Enhancement

#42 Appropriately size footer tap targets to enhance mobile SEO
  src/css/custom.css
Labels: 🪲 Bug, 🎨 Design

#43 Link to the newly released Data Streamer reference docs
  docs/services/data-streamer/stream-types.md
  docs/services/data-streamer/usage.md
  docs/services/events/getting-started.md
Labels: ✏️ Editorial

#44 Fix unsupported style property in docusaurus config
  docusaurus.config.js
Labels: 🪲 Bug

#47 Sidebar enhancements: Auto-collapse categories and add hide option
  docusaurus.config.js
  src/css/custom.css
Labels: ✨ Enhancement

#48 Remove inaccurate FaaS information on Security page
  docs/services/security.md
Labels: 💬 Feedback

#49 Change navbar title from Developers to Documentation
  docusaurus.config.js
Labels: 💬 Feedback

#46 SDOCS-181-Quickstart-guide-content-change-requests
  docs/quickstart/getting-started.md
  docs/quickstart/registering-sims.md
  docs/services/global-iot-sim.md
Labels: 💬 Feedback

#45 Language sweep of remaining migration pages, emnify naming cleanup
  docs/cellular-iot.md
  docs/glossary.md
  docs/sdks/python/help.md
  docs/services/data-streamer/available-integrations.md
  docs/services/data-streamer/stream-types.md
  docs/services/events/event-types.md
  docusaurus.config.js
Labels: ✏️ Editorial, ✨ Enhancement

#53 Increase padding around main content on smaller screens
  src/css/custom.css
Labels: 💬 Feedback, 🎨 Design

#54 Rebrand Cellular IoT Platform infographic and write alt text
  docs/assets/infographic-emnify-cellular-iot-platform.png
  docs/cellular-iot.md
Labels: ✨ Enhancement

#56 Create issue and pull request templates
  .github/ISSUE_TEMPLATE/ask-a-question-or-give-us-feedback.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚙️ Meta

#57 Fix links to broken pages
  docs/quickstart/devices/getting-the-first-device-online.md
  docs/sdks/python/concepts.md
  docs/services/data-streamer/usage.md
  docs/services/events/event-types.md
  docs/services/events/usage.md
  docs/services/global-iot-sim.md
  docs/services/security.md
Labels: 🪲 Bug, 💬 Feedback

#55 Fix error in Teltonika GPS APN configuration command
  docs/quickstart/devices/gps-trackers.md
Labels: 🪲 Bug, 💬 Feedback

#58 Add OneTrust consent and cookie management
  docusaurus.config.js
  static/scripts/optanonWrapper.js
Labels: ⚙️ Meta

#63 Fix Prettier config to use double quotes
  .eslintrc.js
  .prettierignore
  .prettierrc
  babel.config.js
  docusaurus.config.js
  sidebars.js
  src/css/custom.css
  src/theme/NotFound.js
  src/theme/NotFound.module.css
  static/scripts/optanonWrapper.js
Labels: ✨ Enhancement, 👀 Ready for review

#61 Add Heap analytics script
  docusaurus.config.js
  static/scripts/heapAnalytics.js
Labels: ⚙️ Meta

#62 Implement Google Tag Manager and JENTIS Tag Manager scripts
  docusaurus.config.js
  static/scripts/googleTagManager.js
  static/scripts/jentisTagManager.js
Labels: ⚙️ Meta

#64 Update event types page ToC to show all events
  docs/services/events/event-types.md
Labels: 💬 Feedback

#66 Implemented Varun's suggestions where possible
  docs/services/assets/check-mark-3-24.png
  docs/services/assets/x-mark-24.png
  docs/services/endpoint-management-and-group-policies.md
  docs/services/events/event-types.md
  docs/services/sim-life-cycle-management.md
  docs/services/user-management.md
Labels: ✨ Enhancement, 💬 Feedback

#52 Configure site for our subdomain
  docusaurus.config.js
  src/theme/NotFound.js
Labels: 👀 Ready for review, 🛑 Blocked

#68 Upgrade Docusaurus packages to the latest version
  package.json
  yarn.lock
Labels: 📦 Dependencies

#69 Apply proper linting to scripts directory
  docusaurus.config.js
  static/scripts/heapAnalytics.js
  static/scripts/jentisTagManager.js
Labels: ✨ Enhancement

#70 Create CNAME
  static/CNAME
Labels: 🪲 Bug, 👀 Ready for review

#72 Actually add Heap analytics app ID to workflow
  .github/workflows/deploy.yml
  docusaurus.config.js
  static/scripts/heapAnalytics.js
Labels: 🪲 Bug
