Repository emnify/product-docs, pull requests merged in 2023-08, with the labels that each got.

#154 Add filter and search UI description to Connected devices page
  .github/vale/styles/emnify/spelling-exceptions.txt
  docs/portal/assets/check-mark-3-24.png
  docs/portal/assets/check-simple.svg
  docs/portal/assets/close.svg
  docs/portal/assets/x-mark-24.png
  docs/portal/roles.md
  docs/portal/sims-and-devices/assets/portal-connected-devices-filters-tag.png
  docs/portal/sims-and-devices/assets/portal-connected-devices-filters.png
  docs/portal/sims-and-devices/assets/portal-connected-devices-search.png
  docs/portal/sims-and-devices/connected-devices.md
Labels: ✏️ Editorial

#155 Remove text-decoration exceptions for anchor elements in tables
  src/css/custom.css
Labels: 🎨 Design

#158 Update GitHub templates based on frequent feedback
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 👀 Ready for review, ⚙️ Meta

#157 Remove beta tag from Workspaces description and guides
  docs/how-tos/workspaces/create.md
  docs/how-tos/workspaces/link.md
  docs/how-tos/workspaces/switch.md
  docs/portal/organization/workspaces.md
Labels: ✏️ Editorial, 👀 Ready for review

#151 Create CI pipeline to validate content with Vale
  .github/workflows/vale.yml
  .vale.ini
Labels: 👀 Ready for review, ⚙️ Meta

#161 Set minimum alert level to error on Vale CI
  .github/vale/README.md
  .github/workflows/vale.yml
  DEVELOPMENT.md
Labels: 🪲 Bug

#160 Implement Markdownlint for Markdown file formatting
  .github/vale/README.md
  .github/vale/styles/Vocab/emnify/accept.txt
  .markdownlint.jsonc
  .prettierignore
  CONTRIBUTING.md
  DEVELOPMENT.md
  docs/glossary.md
  docs/graphql/graphiql-ide.md
  docs/graphql/preview.md
  docs/how-tos/multi-inclusive-volumes.md
  docs/how-tos/sso/google-cloud-platform.md
  docs/how-tos/sso/microsoft-active-directory.md
  docs/how-tos/sso/troubleshooting.md
  docs/how-tos/two-factor-authentication.md
  docs/how-tos/workspaces/create.md
  docs/how-tos/workspaces/link.md
  docs/how-tos/workspaces/switch.md
  docs/iot-supernetwork.md
  docs/portal/dashboard.md
  docs/portal/integrations/application-tokens.md
  docs/portal/organization/billing.md
  docs/portal/organization/employees.md
  docs/portal/organization/subscription.md
  docs/portal/organization/workspaces.md
  docs/portal/roles.md
  docs/portal/sims-and-devices/connected-devices.md
  docs/portal/sims-and-devices/device-policies.md
  docs/portal/sims-and-devices/troubleshooting.md
  docs/portal/sms.md
  docs/quickstart/apn-configuration/cellular-modules.md
  docs/quickstart/apn-configuration/gps-trackers.md
  docs/quickstart/apn-configuration/industrial-routers.md
  docs/quickstart/index.md
  docs/quickstart/order-sims.md
  docs/quickstart/register-sims.md
  docs/quickstart/troubleshooting.md
  docs/rest/authentication.md
  docs/rest/sms-operations.md
  docs/sdks/concepts.md
  docs/sdks/java/quickstart.md
  docs/sdks/python/quickstart.md
  docs/services/connectivity/global-iot-sim.md
  docs/services/connectivity/sim-lifecycle-management.md
  docs/services/connectivity/sms.md
  docs/services/network/cloud-connect.md
  docs/services/network/global-iot-network.md
  docs/services/network/openvpn.md
  docs/services/platform/data-streamer/connection-types.md
  docs/services/platform/data-streamer/data-streams.md
  docs/services/platform/data-streamer/index.md
  docs/services/platform/data-streamer/stream-types.md
  docs/services/platform/data-streamer/usage.md
  docs/services/platform/events/event-types.md
  docs/services/platform/events/index.md
  docs/services/platform/events/usage.md
  docs/services/platform/integration-guides/index.md
  docs/services/platform/security.md
  docs/support.md
  package.json
Labels: ✨ Enhancement, 👀 Ready for review, ⚙️ Meta

#163 Add 'Set the environment variables' section to development guide
  .github/vale/styles/Vocab/emnify/accept.txt
  DEVELOPMENT.md
Labels: 👀 Ready for review, ⚙️ Meta

#165 Migrate SIM registration guide from the Knowledge Base
  docs/quickstart/apn-configuration/index.md
  docs/quickstart/assets/portal-get-started-collapsible-register-sims-menu-item.png
  docs/quickstart/assets/portal-sim-registration-enter-bic1.png
  docs/quickstart/assets/portal-sim-registration-enter-bic2.png
  docs/quickstart/assets/portal-sim-registration-sim-batch.png
  docs/quickstart/create-device.md
  docs/quickstart/register-sims.md
  docs/quickstart/troubleshooting.md
Labels: ✏️ Editorial, 👀 Ready for review

#153 Adapted Java quickstart to structure of Python quickstart
  docs/sdks/java/quickstart.md
Labels: ✏️ Editorial, ✨ Enhancement

#169 Run markdownlint on Java SDK Quickstart guide
  docs/sdks/java/quickstart.md
Labels: ⚙️ Meta

#162 Update SIM and device status definitions based on CSM feedback
  docs/glossary.md
  docs/graphql/graphiql-ide.md
  docs/portal/dashboard.md
  docs/portal/sims-and-devices/connected-devices.md
  docs/services/connectivity/sim-lifecycle-management.md
Labels: 💬 Feedback

#167 Center images horizontally in main content
  src/css/custom.css
Labels: 👀 Ready for review, 🎨 Design

#168 Fix invalid DOM properties in Global IoT SIM tables
  docs/services/connectivity/global-iot-sim.md
Labels: 🪲 Bug

#171 Create table on SIM inventory page to describe each property shown in Details
  docs/portal/sims-and-devices/assets/portal-sim-inventory-search-bar-attributes.png
  docs/portal/sims-and-devices/sim-inventory.md
  docs/services/connectivity/sim-lifecycle-management.md
Labels: ✏️ Editorial, 👀 Ready for review

#166 Swap SIM registration illustration for BIC1 and BIC2
  .github/vale/styles/Vocab/emnify/accept.txt
  DEVELOPMENT.md
  docs/graphql/graphiql-ide.md
  docs/portal/roles.md
  docs/portal/sims-and-devices/connected-devices.md
  docs/quickstart/assets/sim-registration-bic1.svg
  docs/quickstart/assets/sim-registration-bic2.svg
  docs/quickstart/register-sims.md
  src/css/custom.css
Labels: ✏️ Editorial

#173 Update the GraphQL authentication process
  docs/graphql/assets/graphiql-default-query.png
  docs/graphql/assets/portal-integrations-application-tokens-add-token-button.png
  docs/graphql/assets/portal-integrations-application-tokens-add-token-form.png
  docs/graphql/assets/portal-integrations-application-tokens-add-token-token-created.png
  docs/graphql/assets/portal-integrations-application-tokens.png
  docs/graphql/graphiql-ide.md
  docs/graphql/preview.md
Labels: ✏️ Editorial, 👀 Ready for review

#170 Warn that emnify charges for activated SIMs, not devices
  docs/glossary.md
  docs/portal/organization/billing.md
  docs/portal/sims-and-devices/assets/portal-dashboard-unused-sims-warning.png
  docs/portal/sims-and-devices/connected-devices.md
  docs/services/connectivity/sim-lifecycle-management.md
Labels: 💬 Feedback, 👀 Ready for review

#172 Create table on Connected devices to describe properties shown in Details
  .github/vale/styles/emnify/spelling-exceptions.txt
  docs/portal/sims-and-devices/assets/device-details.png
  docs/portal/sims-and-devices/connected-devices.md
  docs/quickstart/apn-configuration/index.md
  docs/quickstart/troubleshooting.md
Labels: ✏️ Editorial

#175 Clean up Device policies page and add direct Portal link to Coverage Policies section
  docs/portal/sims-and-devices/assets/coverage-policies.png
  docs/portal/sims-and-devices/device-policies.md
Labels: ✏️ Editorial
