Repository emnify/product-docs, pull requests merged in 2023-09, with the labels that each got.

#152 New structure and design of python SDK examples
  docs/sdks/python/examples.md
Labels: ✏️ Editorial, ✨ Enhancement

#178 Add 'User switched workspaces' event type
  docs/services/platform/events/event-types.md
Labels: ✏️ Editorial, 👀 Ready for review

#181 Deleted redundant hint information in text flow
  docs/services/platform/events/index.md
Labels: ✏️ Editorial

#184 Add screenshot annotation guidelines to internal docs
  CONTRIBUTING.md
  docs/services/platform/events/index.md
Labels: 🎨 Design, ⚙️ Meta

#183 Delete unnecessary Portal screenshots
  docs/how-tos/assets/portal-user-settings-2fa-enabled.png
  docs/how-tos/assets/portal-user-settings-2fa-password.png
  docs/how-tos/assets/portal-user-settings-trusted-devices.png
  docs/how-tos/assets/portal-user-settings.png
  docs/how-tos/sso/assets/portal-organization-settings-sso.png
  docs/how-tos/sso/microsoft-active-directory.md
  docs/how-tos/two-factor-authentication.md
  docs/portal/integrations/application-tokens.md
  docs/portal/integrations/assets/application-tokens-add-first-token.png
  docs/portal/integrations/assets/application-tokens-add-token-dialog.png
  docs/portal/integrations/assets/integrations-application-tokens.png
  docs/portal/integrations/assets/token-created.png
  docs/portal/organization/assets/org-user-list.png
  docs/portal/organization/assets/workspaces-create.png
  docs/portal/organization/assets/workspaces-created.png
  docs/portal/organization/employees.md
  docs/portal/organization/workspaces.md
  docs/portal/sims-and-devices/assets/usage-data-current-month.png
  docs/portal/sims-and-devices/assets/usage-data-last-hour.png
  docs/portal/sims-and-devices/troubleshooting.md
  docs/quickstart/assets/portal-nav-organization-settings-subscription.png
  docs/quickstart/assets/sim-apn-setup.png
  docs/quickstart/assets/sim-create-and-activate.png
  docs/quickstart/assets/sim-create-new-device-with-name-tags.png
  docs/quickstart/assets/sim-create-new-device.png
  docs/quickstart/assets/sim-enter-bic1-register-sim-card.png
  docs/quickstart/assets/sim-registered-create-device.png
  docs/quickstart/index.md
  docs/quickstart/register-sims.md
  docs/services/connectivity/assets/portal-device-policies-configure-webhook.png
  docs/services/connectivity/sms.md
  docs/services/platform/assets/portal-add-custom-dns.png
  docs/services/platform/assets/portal-configure-custom-dns.png
  docs/services/platform/data-streamer/assets/portal-integrations-data-streams-add-buttons.png
  docs/services/platform/data-streamer/assets/portal-integrations-data-streams-panel.png
  docs/services/platform/data-streamer/usage.md
  docs/services/platform/security.md
Labels: ✨ Enhancement, 👀 Ready for review

#186 Rename existing Portal asset files to match naming conventions
  docs/portal/assets/portal-connected-devices-open-sms-console.png
  docs/portal/assets/portal-connected-devices-sms-bulk-send.png
  docs/portal/assets/portal-device-details-open-sms-console.png
  docs/portal/assets/portal-device-sms-console.png
  docs/portal/organization/assets/portal-organization-employees-invite.png
  docs/portal/organization/assets/portal-organization-settings-menu.png
  docs/portal/organization/employees.md
  docs/portal/organization/settings.md
  docs/portal/sims-and-devices/assets/portal-connected-devices-bulk-enable-disable.png
  docs/portal/sims-and-devices/assets/portal-connected-devices-bulk-reset.png
  docs/portal/sims-and-devices/assets/portal-connected-devices-reset-connectivity.png
  docs/portal/sims-and-devices/assets/portal-connected-devies-bulk-policy-change.png
  docs/portal/sims-and-devices/assets/portal-device-details-events.png
  docs/portal/sims-and-devices/assets/portal-device-details-reset-connectivity.png
  docs/portal/sims-and-devices/assets/portal-events-create-pdp-context-success-and-failure.png
  docs/portal/sims-and-devices/assets/portal-service-policies-sms-interface-add-webhook.png
  docs/portal/sims-and-devices/assets/portal-service-policies-sms-interface-configure-webhook.png
  docs/portal/sims-and-devices/assets/portal-service-policies-sms-interface-smpp.png
  docs/portal/sims-and-devices/connected-devices.md
  docs/portal/sims-and-devices/device-policies.md
  docs/portal/sims-and-devices/troubleshooting.md
  docs/portal/sms.md
Labels: ⚙️ Meta

#192 Update Integration Guide links to avoid redirects
  docs/services/platform/integration-guides/index.md
Labels: 💬 Feedback

#191 Upgrade Docusaurus to v2.4.3
  package.json
  yarn.lock
Labels: ⚙️ Meta
