Repository emnify/product-docs, pull requests merged in 2023-02, with the labels that each got.

#76 Update Python SDK docs for public release
  docs/glossary.md
  docs/sdks/python/getting-started.md
  docs/sdks/python/help.md
  sidebars.js
Labels: ✏️ Editorial, 👀 Ready for review

#75 Add initial Java SDK documentation
  docs/sdks/concepts.md
  docs/sdks/java/examples.md
  docs/sdks/java/getting-started.md
  docs/sdks/java/help.md
  docs/sdks/python/examples.md
  docs/sdks/python/getting-started.md
  sidebars.js
Labels: ✏️ Editorial

#78 Extract REST API documentation into its own area of the site
  docs/rest-api/authentication.md
  docs/rest-api/getting-started.md
  docs/rest-api/sms-operations.md
  docusaurus.config.js
  sidebars.js
  src/css/custom.css
Labels: ✏️ Editorial, :bulb: Idea

#79 Clean up links to not rely on relative paths
  docs/services/data-streamer/stream-types.md
  docs/services/events/event-types.md
  docs/services/events/usage.md
Labels: ✨ Enhancement

#77 Add troubleshooting toggle for phone number verification issues in Quickstart
  docs/quickstart/getting-started.md
  src/css/custom.css
Labels: ✏️ Editorial, ✨ Enhancement

#82 Update getting-started.md
  docs/quickstart/getting-started.md
Labels: ✏️ Editorial

#89 Show "Last updated" timestamps on all documentation pages
  docusaurus.config.js
Labels: ✨ Enhancement

#88 Create Integration Guides index page
  docs/integration-guides/index.md
  sidebars.js
Labels: ✏️ Editorial

#92 Update Glossary terms related to the SIM EID implementation
  docs/assets/infographic-eid-digits.png
  docs/assets/infographic-iccid-digits.png
  docs/glossary.md
Labels: ✏️ Editorial

#94 Added a Home menu item to the navbar
  docusaurus.config.js
Labels: 🎨 Design

#90 Clarify the Industrial routers APN configuration
  docs/quickstart/devices/industrial-routers.md
Labels: ✏️ Editorial

#83 First attempt at providing images with borders and rounding
  docs/services/sms.md
  docs/sso/microsoft-active-directory.md
  src/css/custom.css
Labels: ✨ Enhancement, 🎨 Design, :bulb: Idea
