Repository emnify/product-docs, pull requests merged in 2023-03, with the labels that each got.

#96 Implement Algolia DocSearch functionality
  docusaurus.config.js
Labels: ✨ Enhancement, 💬 Feedback

#95 Mention the initial pre-paid credit in the Quickstart guide
  docs/quickstart/getting-started.md
Labels: ✏️ Editorial

#98 Adjust links to Integration page of Portal to use header anchors
  docs/glossary.md
  docs/rest-api/authentication.md
  docs/sdks/python/getting-started.md
  docs/services/data-streamer/usage.md
  docs/services/events/usage.md
  docs/services/no-code-workflow-automation.md
  docs/services/openvpn.md
  docs/services/sms.md
Labels: ✨ Enhancement

#101 Remove references to shipment fees in Quickstart guide
  docs/quickstart/assets/portal-dashboard-get-started-get-sims-button.png
  docs/quickstart/assets/portal-order-evaluation-pack-invoice-shipping-details.png
  docs/quickstart/getting-started.md
Labels: ✏️ Editorial

#107 Publish initial GraphQL API documentation
  docs/graphql/assets/graphiql-default-headers.png
  docs/graphql/assets/graphiql-default-query-response.png
  docs/graphql/assets/graphiql-default-query.png
  docs/graphql/assets/graphiql-default.png
  docs/graphql/assets/graphiql-docs-query-myuser-user-organisation.png
  docs/graphql/assets/graphiql-docs-query-myuser-user.png
  docs/graphql/assets/graphiql-docs-query-myuser.png
  docs/graphql/assets/graphiql-graphiql-explorer-endpoints.png
  docs/graphql/assets/graphiql-query-autocomplete.png
  docs/graphql/assets/graphiql-sidebar-show-documentation-explorer-button.png
  docs/graphql/assets/graphiql-sidebar-show-graphiql-explorer-button.png
  docs/graphql/assets/graphiql-sidebar-show-history-button.png
  docs/graphql/assets/portal-integrations-application-tokens-add-token-button.png
  docs/graphql/assets/portal-integrations-application-tokens-add-token-form.png
  docs/graphql/assets/portal-integrations-application-tokens-add-token-token-created.png
  docs/graphql/assets/portal-integrations-application-tokens.png
  docs/graphql/preview.md
  docs/graphql/using-graphiql.md
  docusaurus.config.js
  sidebars.js
  src/css/custom.css
Labels: ✏️ Editorial

#41 Write descriptive README
  CONTRIBUTING.md
  README.md
  package.json
Labels: 👀 Ready for review, ⚙️ Meta

#100 Migrate multi-inclusive volumes how-to from Knowledge Base to product-docs
  docs/how-tos/assets/portal-connected-devices-bulk-actions-change-coverage-policy-modal.png
  docs/how-tos/assets/portal-connected-devices-bulk-actions-more-change-coverage-policy.png
  docs/how-tos/assets/portal-connected-devices-details-button.png
  docs/how-tos/assets/portal-connected-devices-details-device-policies-coverage-policy-dropdown.png
  docs/how-tos/assets/portal-connected-devices-details-device-policies-coverage-policy-edit-button.png
  docs/how-tos/assets/portal-connected-devices-select-multiple-devices.png
  docs/how-tos/assets/portal-connected-devices.png
  docs/how-tos/assets/portal-device-policies-coverage-policies-details-button.png
  docs/how-tos/assets/portal-device-policies-coverage-policies-details-inclusive-volume.png
  docs/how-tos/assets/portal-device-policies-coverage-policies-details-tariff.png
  docs/how-tos/assets/portal-device-policies-coverage-policies.png
  docs/how-tos/assets/portal-device-policies.png
  docs/how-tos/index.md
  docs/how-tos/multi-inclusive-volumes.md
  sidebars.js
Labels: ✏️ Editorial

#80 Create DEVELOPERS guide
  DEVELOPERS.md
Labels: ⚙️ Meta

#109 Add generating code section to GraphiQL guide
  docs/graphql/assets/graphiql-default-generate-code-buttons.png
  docs/graphql/using-graphiql.md
Labels: ✏️ Editorial

#113 Upgrade Docusaurus to 2.4.0
  package.json
  yarn.lock
Labels: 👀 Ready for review, 📦 Dependencies

#110 Update development guide to include necessary internal documentation
  CONTRIBUTING.md
  DEVELOPERS.md
  README.md
Labels: ⚙️ Meta

#114 Update IMEI definition to accurately reflect what acronym represents
  docs/glossary.md
  docs/services/security.md
Labels: ✏️ Editorial
