Repository emnify/product-docs, pull requests merged in 2024-01, with the labels that each got.

#224 Fix create device instructions in quickstart guide
  docs/quickstart/create-device.md
Labels: 🪲 Bug, ✏️ Editorial, 👀 Ready for review

#194 Restructure security service page and separate DNS configuration into how-to guide
  docs/how-tos/configure-dns-settings.md
  docs/services/platform/security.md
  sidebars.js
Labels: ✏️ Editorial

#195 Redo of system events usage
  .editorconfig
  docs/services/platform/data-streamer/usage.mdx
  docs/services/platform/events/usage.mdx
Labels: ✏️ Editorial

#190 Restructure device policies page and extract how-to guides
  docs/how-tos/device-policies/assets/portal-connected-devices-bulk-policy-change.png
  docs/how-tos/device-policies/assign-devices-to-policies.md
  docs/how-tos/device-policies/create-coverage-policies.md
  docs/how-tos/device-policies/create-service-policies.md
  docs/how-tos/device-policies/update-existing-policies.md
  docs/portal/sims-and-devices/assets/portal-connected-devices-bulk-reset.png
  docs/portal/sims-and-devices/device-policies.mdx
  sidebars.js
Labels: ✏️ Editorial

#228 Deploy PR previews
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/lint.yml
  .github/workflows/preview.yml
  docs/how-tos/index.md
  docusaurus.config.js
Labels: 👀 Ready for review, ⚙️ Meta

#230 Only run lint workflows on pull requests
  .github/workflows/lint.yml
  .github/workflows/vale.yml
Labels: ⚙️ Meta

#231 Specify the Vale CLI version to use in workflows
  .github/workflows/vale.yml
Labels: 🪲 Bug

#226 Upgrade to Docusaurus v3.1.0
  .vale.ini
  CONTRIBUTING.md
  docs/glossary.md
  docs/graphql/graphiql-ide.mdx
  docs/graphql/preview.md
  docs/how-tos/data-allowances.mdx
  docs/how-tos/device-policies/assign-devices-to-policies.md
  docs/how-tos/device-policies/update-existing-policies.md
  docs/how-tos/multi-factor-authentication.md
  docs/how-tos/sso/google-cloud-platform.md
  docs/how-tos/sso/microsoft-active-directory.mdx
  docs/how-tos/workspaces/create.mdx
  docs/how-tos/workspaces/link.mdx
  docs/how-tos/workspaces/switch.mdx
  docs/portal/integrations/application-tokens.md
  docs/portal/organization/subscription.md
  docs/portal/sims-and-devices/connected-devices.mdx
  docs/portal/sims-and-devices/troubleshooting.mdx
  docs/portal/user-settings.md
  docs/quickstart/apn-configuration/gps-trackers.md
  docs/quickstart/create-device.md
  docs/quickstart/order-sims.mdx
  docs/quickstart/register-sims.mdx
  docs/services/connectivity/sim-lifecycle-management.mdx
  docs/services/connectivity/sms.mdx
  docs/services/network/openvpn.md
  docs/services/platform/data-streamer/integrations.md
  docs/services/platform/data-streamer/stream-types.md
  docs/services/platform/data-streamer/usage.md
  docs/services/platform/events/event-types.md
  docs/services/platform/events/usage.mdx
  docusaurus.config.js
  package.json
  src/theme/NotFound.js
  src/theme/NotFound/Content/index.js
  src/theme/NotFound/Content/index.module.css
  yarn.lock
Labels: 👀 Ready for review, ⚙️ Meta

#233 Restructure styles directory to comply with Vale CLI v3
  .github/vale/styles/config/vocabularies/emnify/accept.txt
  .github/vale/styles/config/vocabularies/emnify/reject.txt
  .github/workflows/vale.yml
Labels: ⚙️ Meta

#234 Update workspace user management documentation
  docs/portal/organization/users.mdx
  docs/portal/organization/workspaces.md
Labels: ✏️ Editorial

#241 Use different markdownlint GitHub Action in lint workflow
  .github/workflows/lint.yml
Labels: 🪲 Bug

#237 Revert Vale changes and designate version 2.30.0
  .github/vale/README.md
  .github/vale/styles/Vocab/emnify/accept.txt
  .github/vale/styles/Vocab/emnify/reject.txt
  .github/workflows/vale.yml
Labels: 🪲 Bug

#232 Remove Heap Analytics config from docs.emnify.com
  .github/workflows/deploy.yml
  docusaurus.config.js
  static/scripts/heapAnalytics.js
Labels: 🪲 Bug, 👀 Ready for review

#242 Limit workflow runs
  .github/vale/README.md
  .github/workflows/content.yml
  .github/workflows/lint.yml
  .github/workflows/preview.yml
  DEVELOPMENT.md
  LICENSE.md
  package.json
Labels: ✨ Enhancement

#243 Add internal docs for pull request previews
  CONTRIBUTING.md
  DEVELOPMENT.md
Labels: ⚙️ Meta

#244 Upgrade to Vale v3.0.3
  .github/vale/README.md
  .github/vale/styles/config/vocabularies/emnify/accept.txt
  .github/vale/styles/config/vocabularies/emnify/reject.txt
  .github/vale/styles/emnify/FixMe.yml
  .github/workflows/content.yml
Labels: ✨ Enhancement

#238 Migrate OpenVPN integration guides from the emnify Knowledge Base
  .github/vale/styles/config/vocabularies/emnify/accept.txt
  docs/services/platform/integration-guides/index.md
  docs/services/platform/integration-guides/openvpn/linux.md
  docs/services/platform/integration-guides/openvpn/macos.md
  docs/services/platform/integration-guides/openvpn/windows.md
  sidebars.js
Labels: ✏️ Editorial

#245 Add OpenVPN guide to integrations overview
  docs/services/platform/integration-guides/index.md
Labels: ✏️ Editorial

#240 Migrate the Trial plan upgrade guide from emnify Knowledge Base
  docs/how-tos/index.md
  docs/how-tos/upgrade-trial-plan.md
  sidebars.js
Labels: ✏️ Editorial

#246 Migrate data and SMS limit configuration guide from emnify Knowledge Base
  .github/vale/styles/emnify/WordList.yml
  docs/how-tos/device-policies/configure-data-sms-limits.md
  docs/how-tos/index.md
  sidebars.js
Labels: ✏️ Editorial

#248 Migrate company name and details update guide from emnify Knowledge Base
  docs/how-tos/index.md
  docs/how-tos/update-company-details.md
  sidebars.js
Labels: ✏️ Editorial, 🏗️ Work in progress

#249 Move data allowance guide under Device Policies category
  docs/how-tos/device-policies/assets/portal-connected-devices-bulk-actions-change-coverage-policy-modal.png
  docs/how-tos/device-policies/assets/portal-connected-devices-bulk-actions-more-change-coverage-policy.png
  docs/how-tos/device-policies/assets/portal-connected-devices-details-button.png
  docs/how-tos/device-policies/assets/portal-connected-devices-details-device-policies-coverage-policy-dropdown.png
  docs/how-tos/device-policies/assets/portal-connected-devices-details-device-policies-coverage-policy-edit-button.png
  docs/how-tos/device-policies/assets/portal-connected-devices-select-multiple-devices.png
  docs/how-tos/device-policies/data-allowances.mdx
  docs/how-tos/index.md
  sidebars.js
Labels: ✨ Enhancement

#250 Migrate add more IP address spaces guide from emnify Knowledge Base
  docs/how-tos/add-ip-address-spaces.md
  docs/how-tos/index.md
  sidebars.js
Labels: ✏️ Editorial

#180 Override default Infima and DocSearch variables with emnify design tokens
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/preview.yml
  .gitignore
  .prettierignore
  DEVELOPMENT.md
  config/importDesignTokens.js
  docs/assets/infographic-emnify-cellular-iot-platform.png
  docs/iot-supernetwork.md
  docs/quickstart/index.md
  docusaurus.config.js
  package.json
  sidebars.js
  src/css/admonition.css
  src/css/badge.css
  src/css/button.css
  src/css/custom.css
  src/css/design-tokens/banner.css
  src/css/design-tokens/button.css
  src/css/design-tokens/checkbox.css
  src/css/design-tokens/colors-light.css
  src/css/design-tokens/input.css
  src/css/design-tokens/search.css
  src/css/design-tokens/support-message.css
  src/css/design-tokens/switch.css
  src/css/design-tokens/text-field.css
  src/css/design-tokens/typescale.css
  src/css/docsearch.css
  src/css/footer.css
  src/css/navbar.css
  src/css/sidebar.css
  src/css/table-of-contents.css
  src/css/toggle.css
  src/theme/Footer/Layout/index.js
  src/theme/NotFound/Content/index.js
  src/theme/NotFound/Content/index.module.css
  static/fonts/Inter-VariableFont_slnt,wght.ttf
  static/img/logo-dark.svg
  static/img/logo-icon-only-dark.svg
  static/img/logo-word-blue-295x80.png
  static/img/logo-word-white-295x80.png
  yarn.lock
Labels: 🎨 Design

#254 Unlist Custom services page
  .github/workflows/lint.yml
  docs/custom-services.md
  sidebars.js
Labels: ✏️ Editorial

#255 Update portal screenshots with outdated UI for select sections
  docs/how-tos/add-ip-address-spaces.mdx
  docs/how-tos/assets/portal-connected-devices.png
  docs/how-tos/assets/portal-integrations-ip-address-space-management-add-ip-address-space-dropdown.png
  docs/how-tos/assets/portal-integrations-ip-address-space-management-add-ip-address-space.png
  docs/how-tos/assets/portal-integrations-ip-address-space-management-delete.png
  docs/how-tos/assets/portal-integrations-ip-address-space-management-ranges.png
  docs/how-tos/device-policies/assets/portal-connected-devices-bulk-actions-change-coverage-policy-modal.png
  docs/how-tos/device-policies/assets/portal-connected-devices-bulk-actions-more-change-coverage-policy.png
  docs/how-tos/device-policies/assets/portal-connected-devices-bulk-policy-change.png
  docs/how-tos/device-policies/assets/portal-connected-devices-details-button.png
  docs/how-tos/device-policies/assets/portal-connected-devices-details-device-policies-coverage-policy-dropdown.png
  docs/how-tos/device-policies/assets/portal-connected-devices-details-device-policies-coverage-policy-edit-button.png
  docs/how-tos/device-policies/assets/portal-connected-devices-select-multiple-devices.png
  docs/portal/assets/portal-connected-devices-open-sms-console.png
  docs/portal/assets/portal-connected-devices-sms-bulk-send.png
  docs/portal/assets/portal-device-details-open-sms-console.png
  docs/portal/organization/assets/org-sso-provider-microsoft.png
  docs/portal/organization/assets/portal-dashboard-workspace-settings-icon.png
  docs/portal/organization/settings.md
  docs/portal/sims-and-devices/assets/portal-connected-devices-bulk-enable-disable.png
  docs/portal/sims-and-devices/assets/portal-connected-devices-reset-connectivity.png
  docs/portal/sims-and-devices/assets/portal-device-details-events.png
  docs/portal/sims-and-devices/assets/portal-device-details-reset-connectivity.png
  docs/portal/sims-and-devices/assets/portal-events-create-pdp-context-success-and-failure.png
  docs/portal/sims-and-devices/assets/portal-events-update-location-failure-and-success.png
  docs/portal/sims-and-devices/assets/portal-service-policies-sms-interface-add-webhook.png
  docs/portal/sims-and-devices/assets/portal-service-policies-sms-interface-configure-webhook.png
  docs/portal/sims-and-devices/assets/portal-service-policies-sms-interface-smpp.png
  docs/portal/sims-and-devices/connected-devices.mdx
  docs/portal/sims-and-devices/device-policies.mdx
  docs/portal/sims-and-devices/troubleshooting.mdx
  docs/portal/sms.mdx
  docs/quickstart/assets/portal-delivery-details-your-order.png
  docs/quickstart/assets/portal-explore-mode.png
  docs/quickstart/assets/portal-get-started-1-2-of-5.png
  docs/quickstart/assets/portal-signup-get-started-with-emnify.png
  docs/quickstart/assets/portal-sim-inventory-order-sim.png
  docs/quickstart/assets/portal-sim-shop-choose-sim-type.png
  docs/quickstart/assets/portal-sim-shop-sim-order-choose-amount-batches.png
  docs/quickstart/assets/portal-sim-shop-sim-order.png
  docs/quickstart/assets/portal-start-with-free-sims.png
  docs/quickstart/assets/portal-your-order-free-batch-of-3.png
  docs/quickstart/order-sims.mdx
Labels: 🎨 Design

#256 Delete unused assets from the docs directory
  docs/assets/generate_app_token.png
  docs/services/assets/catch-hook.png
  docs/services/assets/service-stack.png
  docs/services/assets/sms-zap.png
Labels: 🎨 Design

#257 Edit sidebar labels to better match main header (plus fix pagination)
  docs/how-tos/device-policies/update-existing-policies.md
  docs/how-tos/index.md
  docs/how-tos/update-company-details.md
  docs/quickstart/index.md
  docs/quickstart/troubleshooting.md
  docs/sdks/java/quickstart.md
  docs/sdks/python/quickstart.md
Labels: ✨ Enhancement, 🎨 Design

#258 Remove 'Edit this page' button and update footer
  docusaurus.config.js
Labels: ✨ Enhancement, 🎨 Design

#259 Change support links to internal in OpenVPN page
  docs/services/network/openvpn.md
Labels: ✨ Enhancement

#260 Implement consistent sidebar category behavior and change active colors
  sidebars.js
  src/css/sidebar.css
Labels: 💬 Feedback, 🎨 Design

#261 Update remaining outdated Portal UI screenshots
  docs/graphql/preview.md
  docs/how-tos/device-policies/create-service-policies.md
  docs/how-tos/sso/microsoft-active-directory.mdx
  docs/how-tos/workspaces/assets/portal-sidebar-workspaces-create.png
  docs/how-tos/workspaces/assets/portal-sidebar-workspaces-current-org-icon.png
  docs/how-tos/workspaces/assets/portal-sidebar-workspaces-first-org.png
  docs/how-tos/workspaces/assets/portal-sidebar-workspaces-link.png
  docs/how-tos/workspaces/assets/portal-sidebar-workspaces-main-org-icon.png
  docs/how-tos/workspaces/assets/portal-sidebar-workspaces-org-list.png
  docs/how-tos/workspaces/assets/portal-sidebar-workspaces-second-org.png
  docs/how-tos/workspaces/assets/portal-sidebar-workspaces.png
  docs/how-tos/workspaces/create.mdx
  docs/how-tos/workspaces/link.mdx
  docs/how-tos/workspaces/switch.mdx
  docs/portal/assets/portal-device-sms-console.png
  docs/portal/integrations/no-code.md
  docs/portal/organization/settings.md
  docs/portal/sims-and-devices/assets/portal-dashboard-unused-sim-warning.png
  docs/portal/sims-and-devices/sim-inventory.mdx
  docs/quickstart/apn-configuration/index.md
  docs/sdks/index.md
  docs/sdks/java/quickstart.md
  docs/sdks/python/quickstart.md
  docs/services/connectivity/assets/portal-connected-devices-details-button.png
  docs/services/connectivity/assets/portal-connected-devices-details-open-sms-console.png
  docs/services/connectivity/assets/portal-connected-devices-details-sms-console.png
  docs/services/connectivity/assets/portal-connected-devices-open-sms-console.png
  docs/services/connectivity/assets/portal-connected-devices-sms.png
  docs/services/connectivity/assets/portal-dashboard-unused-sim-warning.png
  docs/services/connectivity/assets/portal-device-policies-add-webhook.png
  docs/services/connectivity/assets/portal-integrations-sms-webhooks-zapier.png
  docs/services/connectivity/assets/portal-send-sms-message-text.png
  docs/services/connectivity/assets/portal-service-policies-sms-interface-add-webhook.png
  docs/services/connectivity/assets/portal-service-policies-sms-interface-configure-webhook.png
  docs/services/connectivity/assets/portal-sms-sent.png
  docs/services/connectivity/sim-lifecycle-management.mdx
  docs/services/connectivity/sms.mdx
  docs/services/platform/assets/portal-integrations-data-streams-details-events-filter.png
  docs/services/platform/assets/portal-integrations-data-streams-status-950x271.png
  docs/services/platform/assets/portal-integrations-data-streams-status.png
  docs/services/platform/data-streamer/assets/portal-integrations-data-streams-add-new-button.png
  docs/services/platform/data-streamer/assets/portal-integrations-data-streams-details-usage.png
  docs/services/platform/data-streamer/index.md
  docs/services/platform/data-streamer/usage.md
  docs/services/platform/events/assets/portal-connected-devices-details-events.png
  docs/services/platform/events/assets/portal-dashboard-events.png
  docs/services/platform/events/assets/portal-sim-inventory-details-events.png
  docs/services/platform/events/index.md
  docs/services/platform/events/usage.mdx
  docs/services/platform/integration-guides/index.md
  docs/services/platform/integration-guides/openvpn/linux.md
Labels: 🎨 Design

#264 Add screenshots to Update company details how-to guide
  docs/how-tos/assets/portal-dashboard-workspace-settings-billing.png
  docs/how-tos/assets/portal-dashboard-workspace-settings-organization-data.png
  docs/how-tos/assets/portal-workspace-settings-billing-payment-information-pay-with-add-payment-method.png
  docs/how-tos/assets/portal-workspace-settings-billing-payment-information-pay-with-change.png
  docs/how-tos/assets/portal-workspace-settings-organization-data-edit-organization-details-save.png
  docs/how-tos/assets/portal-workspace-settings-organization-data-organization-details-edit.png
  docs/how-tos/update-company-details.md
Labels: ✨ Enhancement

#267 Add screenshots to Portal section of OpenVPN integration guides
  .github/vale/styles/Google/Headings.yml
  .github/vale/styles/config/vocabularies/emnify/accept.txt
  docs/services/platform/integration-guides/openvpn/assets/portal-integrations-secure-connection-openvpn-show-instructions.png
  docs/services/platform/integration-guides/openvpn/assets/portal-integrations-secure-connections-openvpn-linux-download-dropdown.png
  docs/services/platform/integration-guides/openvpn/assets/portal-integrations-secure-connections-openvpn-linux-download.png
  docs/services/platform/integration-guides/openvpn/assets/portal-integrations-secure-connections-openvpn-macos-download-dropdown.png
  docs/services/platform/integration-guides/openvpn/assets/portal-integrations-secure-connections-openvpn-macos-download.png
  docs/services/platform/integration-guides/openvpn/assets/portal-integrations-secure-connections-openvpn-windows-download-dropdown.png
  docs/services/platform/integration-guides/openvpn/assets/portal-integrations-secure-connections-openvpn-windows-download.png
  docs/services/platform/integration-guides/openvpn/linux.mdx
  docs/services/platform/integration-guides/openvpn/macos.mdx
  docs/services/platform/integration-guides/openvpn/windows.mdx
Labels: ✨ Enhancement

#266 Update data and SMS limit how-to guide and add screenshots
  docs/how-tos/device-policies/assets/portal-device-policies-service-policies-data-usage-data-limit-example.png
  docs/how-tos/device-policies/assets/portal-device-policies-service-policies-details-data-usage-limit-dropdown.png
  docs/how-tos/device-policies/assets/portal-device-policies-service-policies-details-data-usage.png
  docs/how-tos/device-policies/assets/portal-device-policies-service-policies-details-sms-receiving-limit-dropdown.png
  docs/how-tos/device-policies/assets/portal-device-policies-service-policies-details-sms-receiving-limit-example.png
  docs/how-tos/device-policies/assets/portal-device-policies-service-policies-details-sms-usage.png
  docs/how-tos/device-policies/assets/portal-device-policies-service-policies-details.png
  docs/how-tos/device-policies/configure-data-sms-limits.mdx
  docs/how-tos/update-company-details.mdx
Labels: ✨ Enhancement

#269 Migrate configure DNS settings guide from emnify Knowledge Base
  docs/how-tos/configure-dns-settings.md
  docs/how-tos/device-policies/assets/portal-device-policies-service-policies-details-more-options-configure-custom-dns.png
  docs/how-tos/device-policies/assets/portal-device-policies-service-policies-details-more-options-custom-dns-add.png
  docs/how-tos/device-policies/assets/portal-device-policies-service-policies-details-more-options-custom-dns-edit.png
  docs/how-tos/device-policies/assets/portal-device-policies-service-policies-details-more-options-custom-dns.png
  docs/how-tos/device-policies/assets/portal-device-policies-service-policies-more-options-custom-dns-remove.png
  docs/how-tos/device-policies/assets/portal-device-policies-service-policies-more-options-custom-dns-save.png
  docs/how-tos/device-policies/configure-dns-settings.mdx
  sidebars.js
Labels: ✏️ Editorial

#265 Update Trial upgrade flow based on current UI and add screenshots
  docs/how-tos/assets/portal-sidebar-trial-plan-choose-a-plan.png
  docs/how-tos/assets/portal-workspace-settings-subscription-data-plan-upgrade-plan-configuration.png
  docs/how-tos/assets/portal-workspace-settings-subscription-trial-expired-upgrade-data-plan.png
  docs/how-tos/assets/portal-workspace-settings-subscription-upgrade-data-plan-confirm-coverage-profile-confirm.png
  docs/how-tos/assets/portal-workspace-settings-subscription-upgrade-data-plan-pricing-get-started.png
  docs/how-tos/upgrade-trial-plan.md
  docs/how-tos/upgrade-trial-plan.mdx
Labels: ✨ Enhancement

#270 Reference API guide for configuring DNS settings
  docs/how-tos/device-policies/configure-dns-settings.mdx
  docs/how-tos/index.md
Labels: ✨ Enhancement

#271 Migrate block operators guide from emnify Knowledge Base
  docs/how-tos/assets/portal-connected-devices-bulk-actions-more-block-operators.png
  docs/how-tos/assets/portal-connected-devices-bulk-actions-networks-blocklist-modal-dropdown.png
  docs/how-tos/assets/portal-connected-devices-bulk-actions-networks-blocklist-modal-save.png
  docs/how-tos/assets/portal-connected-devices-details.png
  docs/how-tos/assets/portal-connected-devices-select-multiple-devices.png
  docs/how-tos/assets/portal-device-details-general-blocked-operators-networks-blocklist-dropdown.png
  docs/how-tos/assets/portal-device-details-general-status-blocked-operators-edit.png
  docs/how-tos/assets/portal-device-details-general-status-blocked-operators-empty-edit.png
  docs/how-tos/assets/portal-device-details-general-status-blocked-operators-networks-blocklist-remove.png
  docs/how-tos/assets/portal-device-details-general-status-blocked-operators-two.png
  docs/how-tos/assets/portal-device-details-general-status-blocked-operators.png
  docs/how-tos/block-operators.mdx
  docs/how-tos/index.md
  sidebars.js
Labels: ✏️ Editorial
